sudo: required

services:
  - docker

install: true

before_script:
  -   - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register
  - docker pull show0k/miniconda-armv7
script:
  
  - docker run -it show0k/miniconda-armv7 uname -a

